### ISSUE TITLE
Editable list - Spacing issue

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-ui#16]
We should add some spacing for the following case
<img width="1288" alt="Screenshot 2019-07-01 at 17 29 16" src="https://user-images.githubusercontent.com/12560939/60452302-2716b280-9c26-11e9-8ab1-13e784f30c7a.png">

**Comment by prince-patel23** [comment]
@ConsM I'm having trouble locating this particular page. Can you assist me in finding it?

**Comment by lghiur** [comment]
@prince-patel23 what is your use case? what are you looking for in particular?

**Comment by lghiur** [comment]
This issue is no longer valid. Closing this atm.
